#! /usr/bin/env python3

# Generate charlieplexing lookup table

import sys

def fn(c):
    return ord(c.lower()) - ord('a')

sys.stdout.write("/* Generated by gen-board-map.py */\n")

fn = sys.stdin.readline().strip().index

while True:
    l2 = sys.stdin.readline()
    if l2 == "":
        break;

    y = zip(*[iter(map(fn, l2.split()))]*2)
    for (a, k) in y:
        sys.stdout.write("PIXEL(%d,%d), " % (a, k))
    sys.stdout.write("\n")
